CREATE TABLE  "INCIDENTES" 
   (	"ID" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"TIPO_ID" NUMBER, 
	"TIEMPO_INICIO" TIMESTAMP (6), 
	"TIEMPO_FINAL" TIMESTAMP (6), 
	"DESDE_LUGAR" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"HASTA_LUGAR" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"LONGITUD_METROS" NUMBER, 
	 CONSTRAINT "INCIDENTES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/