CREATE TABLE  "INCIDENTES_COORDENADAS" 
   (	"ID" NUMBER, 
	"ID_INCIDENTE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"LONGITUD" NUMBER, 
	"LATITUD" NUMBER, 
	"FECHA_ACTUALIZACION" TIMESTAMP (6), 
	 CONSTRAINT "INCIDENTES_COORDENADAS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
