CREATE TABLE  "PAGINAS" 
   (	"ID" NUMBER, 
	"PAGINA" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"FECHA" TIMESTAMP (6), 
	 CONSTRAINT "PAGINAS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
